version: '3'
services:
  postgres:
    image: postgres:14.4
    container_name: db-dix-postgre
    environment:
      - POSTGRES_USER=userdix
      - POSTGRES_DB=dbdix
      - POSTGRES_PASSWORD=dix_app1234
    ports:
      - 5441:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
    pg-data: